<a href="https://colab.research.google.com/github/s104004498/work/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [1]:
import pandas as pd
print("pandas version: %s" % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)


pandas version: 0.24.2
matplotlib version: 3.0.3
numpy version: 1.16.3
scikit-learn version: 0.20.3


#建立array陣列

使用np.array()建立陣列

In [2]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


使用numpy提供的創建函數直接生成

In [3]:
import numpy as np
x=np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
y=np.arange(2, 3, 0.1) # start, end, step
print(y)


[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [10]:
import numpy as np
#z=np.linspace(1., 4., 6) # start, end, num

z=np.linspace(2.0, 3.0, num=5, retstep=True)
print(z)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


#屬性


In [0]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

ar2.shape

In [12]:
ar2.ndim


2

#NDarray的各種運算

###reshape()

In [15]:
x = np.arange(4)
x


array([0, 1, 2, 3])

In [17]:
x2 = x.reshape(4,1)
x2
x2.shape

(4, 1)

#作業

In [18]:
import numpy as np

a=np.array([[0,1],[2,3]])

print(a)



[[0 1]
 [2 3]]


In [20]:
import numpy as np

x=np.arange(2,10).reshape(4,2)
x

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
import numpy as np

x=np.arange(24).reshape(4,3,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])